-- Run this in your Supabase SQL Editor

create table menu_items (
  id bigint generated by default as identity primary key,
  producto text not null,
  cantidad integer default 0,
  precio numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
